# Generated by Django 5.0.1 on 2024-01-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_de_profil',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/'),
        ),
    ]
