# Generated by Django 5.0.1 on 2024-02-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacance', '0002_alter_user_image_de_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='recu',
            field=models.ImageField(blank=True, null=True, upload_to='images/recus/'),
        ),
    ]
