# Generated by Django 5.0.1 on 2024-02-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacance', '0003_commande_recu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='recu',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/recus/'),
        ),
    ]
